In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df_fr = pd.read_csv("../data/FrenchOpen-women-2013.csv")

In [3]:
df_us = pd.read_csv("../data/USOpen-women-2013.csv")

In [4]:
df_us.rename(columns={"Player 1": "Player1", "Player 2": "Player2"}, inplace=True)

In [5]:
def keep_last_name(df):
    df["Player1"] = df["Player1"].str.split(" ").str[-1]
    df["Player2"] = df["Player2"].str.split(" ").str[-1]

In [6]:
keep_last_name(df_fr)
keep_last_name(df_us)

In [13]:
df_merged1 = pd.merge(df_fr, df_us, on=["Player1", "Player2"], how="inner", suffixes=("_fr", "_us"))

In [14]:
df_merged1

,Player1,Player2,Round,Result_fr,FNL.1_fr,FNL.2_fr,FSP.1_fr,FSW.1_fr,SSP.1_fr,SSW.1_fr,...,BPC.2_us,BPW.2_us,NPA.2_us,NPW.2_us,TPW.2_us,ST2.1.1,ST2.2_us,ST3.2_us,ST4.2_us,ST5.2_us
0,Cornet,Koehler,1,1,2,0,70,28,30,11,...,4,1,3.0,3.0,NaN,3,2,NaN,NaN,NaN
1,Cornet,Azarenka,3,0,1,2,65,28,35,10,...,18,4,30.0,19.0,NaN,6,6,6.0,NaN,NaN

In [17]:
df_merged2 = pd.merge(df_fr, df_us, left_on=["Player1", "Player2"], right_on=["Player2", "Player1"], how="inner", suffixes=("_fr", "_us"))

In [18]:
df_merged2

Empty DataFrame
Columns: [Player1_fr, Player2_fr, Round, Result_fr, FNL.1_fr, FNL.2_fr, FSP.1_fr, FSW.1_fr, SSP.1_fr, SSW.1_fr, ACE.1_fr, DBF.1_fr, WNR.1_fr, UFE.1_fr, BPC.1_fr, BPW.1_fr, NPA.1_fr, NPW.1_fr, TPW.1_fr, ST1.1_fr, ST2.1_fr, ST3.1_fr, ST4.1_fr, ST5.1_fr, FSP.2_fr, FSW.2_fr, SSP.2_fr, SSW.2_fr, ACE.2_fr, DBF.2_fr, WNR.2_fr, UFE.2_fr, BPC.2_fr, BPW.2_fr, NPA.2_fr, NPW.2_fr, TPW.2_fr, ST1.2, ST2.2_fr, ST3.2_fr, ST4.2_fr, ST5.2_fr, Player1_us, Player2_us, ROUND, Result_us, FNL.1_us, FNL.2_us, FSP.1_us, FSW.1_us, SSP.1_us, SSW.1_us, ACE.1_us, DBF.1_us, WNR.1_us, UFE.1_us, BPC.1_us, BPW.1_us, NPA.1_us, NPW.1_us, TPW.1_us, ST1.1_us, ST2.1_us, ST3.1_us, ST4.1_us, ST5.1_us, FSP.2_us, FSW.2_us, SSP.2_us, SSW.2_us, ACE.2_us, DBF.2_us, WNR.2_us, UFE.2_us, BPC.2_us, BPW.2_us, NPA.2_us, NPW.2_us, TPW.2_us, ST2.1.1, ST2.2_us, ST3.2_us, ST4.2_us, ST5.2_us]
Index: []

[0 rows x 84 columns]

In [20]:
df_merged = pd.concat([df_merged1, df_merged2], ignore_index=True)

In [34]:
df_merged

,Player1,Player2,Round,Result_fr,FNL.1_fr,FNL.2_fr,FSP.1_fr,FSW.1_fr,SSP.1_fr,SSW.1_fr,...,TPW.2_us,ST2.1.1,ST2.2_us,ST3.2_us,ST4.2_us,ST5.2_us,Player1_fr,Player2_fr,Player1_us,Player2_us
0,Cornet,Koehler,1,1,2,0,70,28,30,11,...,NaN,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Cornet,Azarenka,3,0,1,2,65,28,35,10,...,NaN,6,6,6.0,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
df_fr[(df_fr["Player1"] == "Cornet") & (df_fr["Player2"] == "Azarenka")]

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,BPC.2,BPW.2,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2
100,Cornet,Azarenka,3,0,1,2,65,28,35,10,...,9,20,23,32,99,4,6.0,6.0,NaN,NaN

In [32]:
df_us[(df_us["Player1"] == "Cornet") & (df_us["Player2"] == "Azarenka")]

,Player1,Player2,ROUND,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,BPC.2,BPW.2,NPA.2,NPW.2,TPW.2,ST2.1.1,ST2.2,ST3.2,ST4.2,ST5.2
16,Cornet,Azarenka,3,0,1,2,56,44,44,21,...,18,4,30.0,19.0,NaN,6,6,6.0,NaN,NaN

0      False
1      False
2      False
3      False
4      False
       ...
122    False
123    False
124    False
125    False
126    False
Length: 127, dtype: bool